### PR TITLE
added digitalocean extra metrics line to vagrantfile

### PR DESCRIPTION
**Pull request by koshaan**
gives us extra stats on digitalocean https://docs.digitalocean.com/products/monitoring/quickstart/

### CODE REVIEW

**Review by ChadIImus — COMMENTED** [review]
LGTM 🤣🤣🤣🤣

**Review by OzzymanH — APPROVED** [review]
Reviewed

**Review by ChadIImus — COMMENTED** [review]
LGTM

**Comment by koshaan** [comment]
i approve of this message

**Pull request merged**
